wip

diff --git a/build/scripts/common b/build/scripts/common
--- a/build/scripts/common
+++ b/build/scripts/common
@@ -4,7 +4,7 @@
 set -e
 export ENVIRONMENT=demo
 
-cd ../terraform/
+cd ./application-infrastructure/
 
 WORKING_DIR=$(pwd)
 
@@ -12,12 +12,12 @@ ORG="cnn"
 TEAM="zion"
 APPLICATION="iac-codebuild-test"
 
-if aws sts get-caller-identity >/dev/null; then
-    echo "Credentials are up-to-date."
-else
-    echo "[ERROR] Credentials are not up-to-date."
-    exit 1
-fi
+#if aws sts get-caller-identity >/dev/null; then
+#    echo "Credentials are up-to-date."
+#else
+#    echo "[ERROR] Credentials are not up-to-date."
+#    exit 1
+#fi
 
 echo "Org: \"${ORG}\""
 echo "Team: \"${TEAM}\""
@@ -27,5 +27,5 @@ WORKSPACE="${ORG}:${TEAM}:${APPLICATION}:${ENVIRONMENT}"
 echo $WORKSPACE
 pwd
 terraform init
-terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
+#terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"
 echo "Workspace: \"$(terraform workspace show)\""
